n1 = input('Digite alguma coisa: ')
print(n1.isalnum())
print(n1.isalpha())
print(n1.isascii())
print(n1.isdecimal())
print(n1.isdigit())
print(n1.isidentifier())
print(n1.islower())
print(n1.isnumeric())
print(n1.isprintable())
print(n1.isspace())
print(n1.istitle())
print(n1.isupper())