n = input('Digite algo: ')
print('Este algo é do tipo primitivo: {}'.format(type(n)))
print('É alfanumérico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('Está dentro de ASCII? ', n.isascii())
print('É decimal? ', n.isdecimal())
print('É um dígito? ', n.isdigit())
print('É um identificador? ', n.isidentifier())
print('Está em minúsculas? ', n.islower())
print('É um número? ', n.isnumeric())
print('É imprimível? ', n.isprintable())
print('Está em branco? ', n.isspace())
print('Está capitalizado? ', n.istitle())
print('Está em maiúsculas? ', n.isupper())
